---
name: ci

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - master
      - unicorn
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Get latest release
        id: kaniko
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: GoogleContainerTools/kaniko

      - name: Get latest release
        id: jq
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: stedolan/jq

      - name: Get latest release
        id: yq
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: mikefarah/yq

      - name: Get latest release
        id: pushrm
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: christian-korneck/docker-pushrm

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            KANIKO_RELEASE=${{ steps.kaniko.outputs.release }}-debug
            JQ_RELEASE==${{ steps.jq.outputs.release }}
            YQ_RELEASE==${{ steps.yq.outputs.release }}
            PUSHRM_RELEASE==${{ steps.pushrm.outputs.release }}
